#!/usr/bin/env python3
# ---------------------------------------------------------
# File:         trace-pipeline.py
# Version:      V1.0
# System:       DnD-RSR / DnD — D&D 5e Dynamic Reference System
# Module/Role:  Traces all file dependencies from the pipeline
#               entry point (build-all.js) in D&D-Sandbox.
#               Compares against the target pipeline directory
#               to produce a precise copy list with no dead wood.
# Usage:        python trace-pipeline.py --target dnd-rsr
#               python trace-pipeline.py --target dnd
#               Output: pipeline-dependency-report.txt
#                       pipeline-copy-missing-files.ps1
# Changelog:
#   V1.0: Initial version. Separate from trace-dependencies.py
#         because the pipeline has its own entry point (build-all.js),
#         runs in Node.js not the browser, maps pipeline-v3/ in the
#         sandbox to pipeline/ in the target, and has its own
#         exclusion rules (node_modules, generated data, etc.).
# ---------------------------------------------------------

import os
import re
import sys
import argparse
from pathlib import Path

# ---------------------------------------------------------
# PATHS
# ---------------------------------------------------------
SANDBOX_PIPELINE = Path(r"C:\Users\bruce\OneDrive\D&D-Sandbox\pipeline-v3")

TARGETS = {
    "dnd-rsr": Path(r"C:\Users\bruce\OneDrive\DnD-RSR\pipeline"),
    "dnd":     Path(r"C:\Users\bruce\OneDrive\DnD\pipeline"),
}

# ---------------------------------------------------------
# FILES TO ALWAYS INCLUDE
# Not reachable via import chains but needed to run.
# ---------------------------------------------------------
ALWAYS_INCLUDE = [
    "package.json",
    "data/config/source-books-map.json",
]

# ---------------------------------------------------------
# DIRECTORIES TO EXCLUDE
# These exist in the sandbox but must never be copied.
# ---------------------------------------------------------
EXCLUDE_DIRS = [
    "node_modules",
    "Legacy",
    "legacy",
    "tests",
    "data/raw",
    "data/normalized",
    "data/aggregated",
    "data/verified",
]

# ---------------------------------------------------------
# FILES TO EXCLUDE (specific files by name)
# Runtime state and development artefacts.
# ---------------------------------------------------------
EXCLUDE_FILES = {
    "pipeline-needed.flag",
    "id-counter.json",
    "id-counter.json.bak",
    "package-lock.json",     # regenerated by npm install
}

# ---------------------------------------------------------
# EXTENSIONS TO EXCLUDE
# ---------------------------------------------------------
EXCLUDE_EXTENSIONS = {'.bak', '.flag', '.txt', '.md', '.log', '.lnk'}

# ---------------------------------------------------------
# FILE EXTENSIONS TO TRACE (parse for further references)
# ---------------------------------------------------------
TRACE_EXTENSIONS = {'.js', '.mjs'}

# ---------------------------------------------------------
# URL PREFIXES TO SKIP (not local files)
# ---------------------------------------------------------
SKIP_PREFIXES = ('http://', 'https://', '//', 'node:',
                 'path', 'fs', 'url', 'os', 'assert')


# =========================================================
# Reference extraction — Node.js ES module imports only
# =========================================================

def extract_refs_js(content):
    refs = []
    # static: import ... from './...' or '../...'
    refs += re.findall(
        r'''import\s+(?:[\w*{},\s]+\s+from\s+)?['"](\.{1,2}/[^'"]+)['"]''',
        content
    )
    # dynamic: await import('./...')
    refs += re.findall(
        r'''import\s*\(\s*['"](\.{1,2}/[^'"]+)['"]\s*\)''',
        content
    )
    return refs


# =========================================================
# Core tracer
# =========================================================

visited = set()
needed  = set()   # paths relative to SANDBOX_PIPELINE


def is_excluded(path: Path) -> bool:
    if path.name in EXCLUDE_FILES:
        return True
    if path.suffix.lower() in EXCLUDE_EXTENSIONS:
        return True
    rel = str(path).replace('\\', '/')
    for excl in EXCLUDE_DIRS:
        if ('/' + excl + '/') in ('/' + rel + '/'):
            return True
    return False


def resolve_ref(base_file: Path, ref: str) -> Path | None:
    ref = ref.strip()
    if not ref or any(ref.startswith(p) for p in SKIP_PREFIXES):
        return None
    ref = ref.split('?')[0].split('#')[0]
    # Add .js extension if missing
    candidate = (base_file.parent / ref).resolve()
    if not candidate.suffix:
        candidate = candidate.with_suffix('.js')
    try:
        candidate.relative_to(SANDBOX_PIPELINE.resolve())
        return candidate
    except ValueError:
        return None


def process_file(file_path: Path):
    if is_excluded(file_path):
        return
    resolved = file_path.resolve()
    if resolved in visited:
        return
    visited.add(resolved)

    try:
        rel = str(resolved.relative_to(SANDBOX_PIPELINE.resolve()))
    except ValueError:
        return

    needed.add(rel)

    if not resolved.exists():
        return

    if resolved.suffix.lower() not in TRACE_EXTENSIONS:
        return

    try:
        content = resolved.read_text(encoding='utf-8', errors='ignore')
    except Exception:
        return

    for ref in extract_refs_js(content):
        target = resolve_ref(resolved, ref)
        if target:
            process_file(target)


# =========================================================
# PowerShell safe path
# =========================================================

def ps_path(p):
    return f'"{p}"'


# =========================================================
# Main
# =========================================================

def main():
    parser = argparse.ArgumentParser(
        description='Trace pipeline dependencies from D&D-Sandbox to a target.'
    )
    parser.add_argument(
        '--target',
        choices=['dnd-rsr', 'dnd'],
        required=True,
        help='Target pipeline directory: dnd-rsr or dnd'
    )
    args = parser.parse_args()

    target_root = TARGETS[args.target]

    print(f"DnD Pipeline — Dependency Tracer V1.0")
    print(f"Target  : {args.target} → {target_root}")
    print(f"Source  : {SANDBOX_PIPELINE}")
    print()

    if not SANDBOX_PIPELINE.exists():
        print(f"ERROR: Sandbox pipeline not found: {SANDBOX_PIPELINE}")
        return

    if not target_root.exists():
        print(f"Target pipeline directory does not exist: {target_root}")
        print("It will be created by the copy script.")

    # 1. Trace from entry point
    entry = SANDBOX_PIPELINE / "build-all.js"
    if not entry.exists():
        print(f"ERROR: Entry point not found: {entry}")
        return

    print(f"Tracing from: {entry.name}")
    process_file(entry)

    # 2. Always-include files
    for rel in ALWAYS_INCLUDE:
        rel_norm = rel.replace('/', os.sep)
        f = SANDBOX_PIPELINE / rel_norm
        if f.exists() and not is_excluded(f):
            needed.add(str(Path(rel_norm)))

    # 3. Classify each needed file
    ok_list      = []
    copy_list    = []
    nowhere_list = []

    for rel in sorted(needed):
        target_file  = target_root / rel
        sandbox_file = SANDBOX_PIPELINE / rel
        if target_file.exists():
            ok_list.append(rel)
        elif sandbox_file.exists():
            copy_list.append(rel)
        else:
            nowhere_list.append(rel)

    # 4. Build report
    report_lines = [
        f"DnD Pipeline — Dependency Report V1.0",
        f"Target  : {args.target} → {target_root}",
        f"Source  : {SANDBOX_PIPELINE}",
        "",
        f"Total files needed : {len(needed)}",
        f"Present in target  : {len(ok_list)}",
        f"Need copying       : {len(copy_list)}",
        f"Not found anywhere : {len(nowhere_list)}",
        "",
        "=" * 70,
        "FULL FILE LIST  (OK = present | COPY = missing | MISSING = not anywhere)",
        "=" * 70,
    ]
    for rel in sorted(needed):
        target_file  = target_root / rel
        sandbox_file = SANDBOX_PIPELINE / rel
        if target_file.exists():
            report_lines.append(f"  OK      {rel}")
        elif sandbox_file.exists():
            report_lines.append(f"  COPY    {rel}")
        else:
            report_lines.append(f"  MISSING {rel}")

    report_lines += [
        "",
        "=" * 70,
        "FILES TO COPY FROM SANDBOX",
        "=" * 70,
    ]
    report_lines += (
        [f"  {r}" for r in copy_list]
        if copy_list
        else ["  (none — pipeline is complete)"]
    )

    report_lines += [
        "",
        "=" * 70,
        "NOT FOUND IN TARGET OR SANDBOX  (investigate)",
        "=" * 70,
    ]
    report_lines += (
        [f"  {r}" for r in nowhere_list]
        if nowhere_list
        else ["  (none)"]
    )

    # Note about data directories to create
    report_lines += [
        "",
        "=" * 70,
        "EMPTY DIRECTORIES TO CREATE IN TARGET",
        "=" * 70,
        "  pipeline/data/",
        "  pipeline/data/raw/      ← add your source data files here",
        "  pipeline/data/normalized/",
        "  pipeline/data/aggregated/",
        "  pipeline/data/verified/",
        "  pipeline/data/config/",
    ]

    report_text = "\n".join(report_lines)
    print(report_text)

    # Write report next to the target's parent
    report_path = target_root.parent / f"pipeline-dependency-report-{args.target}.txt"
    report_path.write_text(report_text, encoding='utf-8')
    print(f"\nReport saved to: {report_path}")

    # 5. Generate PowerShell copy script
    if copy_list:
        ps_lines = [
            f"# pipeline-copy-missing-files-{args.target}.ps1",
            "# Generated by trace-pipeline.py V1.0",
            "# Review before running.",
            "# Copies pipeline files from sandbox to target.",
            "# Files already in target are NOT touched.",
            "",
            f"$source  = {ps_path(SANDBOX_PIPELINE)}",
            f"$target  = {ps_path(target_root)}",
            "",
            "# Create required data subdirectories",
            r'@("data", "data\raw", "data\normalized", "data\aggregated", "data\verified", "data\config") | ForEach-Object {',
            r'    $d = "$target\$_"',
            r'    if (!(Test-Path $d)) { New-Item -ItemType Directory -Force -Path $d | Out-Null }',
            r'    Write-Output "Directory ready: $_"',
            "}",
            "",
        ]
        for rel in copy_list:
            rel_bs = rel.replace('/', '\\')
            ps_lines += [
                f'$src = "{SANDBOX_PIPELINE}\\{rel_bs}"',
                f'$dst = "{target_root}\\{rel_bs}"',
                r'$dir = Split-Path $dst',
                r'if (!(Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }',
                r'Copy-Item $src $dst',
                f'Write-Output "Copied: {rel_bs}"',
                "",
            ]
        ps_script_path = target_root.parent / f"pipeline-copy-missing-files-{args.target}.ps1"
        ps_script_path.write_text("\n".join(ps_lines), encoding='utf-8')
        print(f"Copy script saved to: {ps_script_path}")
        print("Review the copy script then run it in PowerShell.")
    else:
        print("No files to copy — pipeline is complete.")


if __name__ == '__main__':
    main()
